# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\GitHub\MakerPlusClient\MainWindow.ui'
#
# Created: Sun Oct 12 11:09:14 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(QtGui.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(702, 580)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(390, 70, 291, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.lineEdit_1 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(390, 110, 291, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setObjectName(_fromUtf8("lineEdit_1"))
        self.lineEdit_2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(390, 160, 291, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_3 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(390, 210, 291, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_4 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(390, 260, 291, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.lineEdit_5 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(390, 310, 291, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(390, 360, 291, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.lineEdit_7 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(390, 410, 291, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(390, 460, 291, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.label_event = QtGui.QLabel(self.centralwidget)
        self.label_event.setGeometry(QtCore.QRect(20, 70, 361, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        self.label_event.setFont(font)
        self.label_event.setTextFormat(QtCore.Qt.AutoText)
        self.label_event.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_event.setMargin(0)
        self.label_event.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_event.setObjectName(_fromUtf8("label_event"))
        self.label_1 = QtGui.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(250, 110, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        self.label_1.setFont(font)
        self.label_1.setTextFormat(QtCore.Qt.AutoText)
        self.label_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_1.setMargin(0)
        self.label_1.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 160, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setMargin(0)
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 210, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_3.setMargin(0)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 260, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_4.setMargin(0)
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 310, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_5.setMargin(0)
        self.label_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(250, 360, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_6.setMargin(0)
        self.label_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(250, 410, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_7.setMargin(0)
        self.label_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(250, 460, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_8.setMargin(0)
        self.label_8.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_title = QtGui.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(10, 10, 681, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑"))
        font.setPointSize(20)
        self.label_title.setFont(font)
        self.label_title.setTextFormat(QtCore.Qt.AutoText)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setMargin(0)
        self.label_title.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_title.setObjectName(_fromUtf8("label_title"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 500, 341, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 500, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_9.setMargin(0)
        self.label_9.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit_com = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_com.setGeometry(QtCore.QRect(80, 500, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        self.lineEdit_com.setFont(font)
        self.lineEdit_com.setObjectName(_fromUtf8("lineEdit_com"))
        self.pushButton_openCom = QtGui.QPushButton(self.centralwidget)
        self.pushButton_openCom.setGeometry(QtCore.QRect(160, 500, 151, 31))
        self.pushButton_openCom.setObjectName(_fromUtf8("pushButton_openCom"))
        self.label_return_info_1 = QtGui.QLabel(self.centralwidget)
        self.label_return_info_1.setGeometry(QtCore.QRect(10, 110, 211, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_return_info_1.setFont(font)
        self.label_return_info_1.setTextFormat(QtCore.Qt.AutoText)
        self.label_return_info_1.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_return_info_1.setMargin(0)
        self.label_return_info_1.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_return_info_1.setObjectName(_fromUtf8("label_return_info_1"))
        self.label_return_info_2 = QtGui.QLabel(self.centralwidget)
        self.label_return_info_2.setGeometry(QtCore.QRect(10, 160, 211, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("微软雅黑 Light"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_return_info_2.setFont(font)
        self.label_return_info_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_return_info_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_return_info_2.setMargin(0)
        self.label_return_info_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_return_info_2.setObjectName(_fromUtf8("label_return_info_2"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 702, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "注册", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "签到", None))
        self.label_event.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" \">事件</span></p></body></html>", None))
        self.label_1.setText(_translate("MainWindow", "<html><head/><body><p>参数1</p></body></html>", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>参数2</p></body></html>", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>参数3</p></body></html>", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>参数4</p></body></html>", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>参数5</p></body></html>", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>参数6</p></body></html>", None))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>参数7</p></body></html>", None))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>参数8</p></body></html>", None))
        self.label_title.setText(_translate("MainWindow", "<html><head/><body><p>Maker+ System</p></body></html>", None))
        self.pushButton.setText(_translate("MainWindow", "上传", None))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>串口号：</p></body></html>", None))
        self.pushButton_openCom.setText(_translate("MainWindow", "开启串口", None))
        self.label_return_info_1.setText(_translate("MainWindow", "<html><head/><body><p>Return Info 1<br/></p></body></html>", None))
        self.label_return_info_2.setText(_translate("MainWindow", "<html><head/><body><p>Return Info 2</p></body></html>", None))

